// Signal moderation: OpenAI GPT-4o-mini pass that runs between the raw
// Supabase fetch and what the AE actually reads.
//
// Raw signals from NewsAPI, newsletters, and SEC EDGAR come in with summaries
// generated by Haiku. These are generally accurate but can have:
//   - Overclaims about timing ("just released", "breaking")
//   - Unhedged inferences stated as fact
//   - Imprecise legal/regulatory citations (wrong article numbers, wrong
//     section names)
//   - Vague attribution ("sources say") without grounding
//
// This module sends all signal summaries in a single batch request to
// gpt-4o-mini, which corrects the framing and hedging without changing the
// core substance. Falls back silently to originals on any error or when no
// OpenAI key is present.
//
// Called server-side only (page.tsx). Never called on the hot path of user
// interaction - only during ISR revalidation.

import { getOpenAIClient } from "./openai";
import type { ExternalSignal } from "./external-signals";

// Cheap and fast for single-pass editorial corrections. Not the structured-
// output model (gpt-4o-2024-08-06) because we don't need tool use here.
const MODERATOR_MODEL = "gpt-4o-mini";

// The system prompt is the core of the correction logic. Keep it tight:
// the model should edit, not rewrite. The JSON output contract is explicit
// so we can parse reliably.
const SYSTEM_PROMPT = `You are a signal quality editor for a B2B sales intelligence platform.
Sales reps read your output before customer meetings — accuracy and appropriate hedging matter.

Your task: review AI-generated news signal summaries and correct them before they reach users.

Rules:
1. Hedge unverified claims. Use "reportedly", "according to [publisher/filing]",
   "based on public filings", or "as noted in" where the original states uncertain
   things as fact.
2. Remove timing overclaims. Strip "just released", "breaking", "announced today"
   unless the source directly supports it. Replace with neutral phrasing.
3. Fix imprecise legal or regulatory citations. If an article number or section
   name is wrong or imprecise and you can identify the correct one, fix it. If
   unsure, soften to "under the relevant provision" rather than citing incorrectly.
4. Separate confirmed from inferred. If the original mixes a confirmed event with
   an inference about impact, use a phrase like "suggesting" or "which may indicate"
   for the inferred portion.
5. Never add new information. Only correct framing and precision.
6. Keep each summary under 60 words. If the original is shorter, keep it shorter.
7. If a summary already meets the above standards, return it unchanged.

Input: JSON object with a "signals" array of {id, summary, source} objects.
Output: JSON object with a "signals" array of {id, summary} objects. No other keys.`;

interface ModerationInput {
  id: string;
  summary: string;
  source: string;
}

interface ModerationOutput {
  signals?: { id: string; summary: string }[];
}

// Moderate a batch of signals. Returns a new array with corrected summaries.
// The original signal objects are not mutated. Falls back to originals on any
// error (OpenAI unavailable, parse failure, partial result).
export async function moderateSignals(
  signals: ExternalSignal[],
): Promise<ExternalSignal[]> {
  if (signals.length === 0) return signals;

  const client = getOpenAIClient();
  if (!client) {
    // No OpenAI key configured - return originals. The UI is still correct;
    // it just won't have the hedging pass applied.
    return signals;
  }

  const input: ModerationInput[] = signals.map((s) => ({
    id: s.id,
    summary: s.summary,
    // Give the model attribution context so it can hedge correctly.
    source: s.publisher_canonical_name ?? s.source,
  }));

  try {
    const completion = await client.chat.completions.create({
      model: MODERATOR_MODEL,
      temperature: 0,
      // json_object mode guarantees valid JSON output. The system prompt
      // explicitly describes the JSON contract so the model knows the shape.
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: JSON.stringify({ signals: input }),
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(raw) as ModerationOutput;
    const corrections = new Map(
      (parsed.signals ?? []).map((r) => [r.id, r.summary]),
    );

    return signals.map((s) => {
      const corrected = corrections.get(s.id);
      // Only apply if the corrected summary is non-empty and different.
      // If the model returned the same text, skip the spread to save allocs.
      if (!corrected || corrected === s.summary) return s;
      return { ...s, summary: corrected };
    });
  } catch {
    // Moderation call failed (timeout, API error, JSON parse error).
    // Return originals silently - a raw signal is still better than a blank.
    return signals;
  }
}

// Convenience wrapper for the Record<accountId, ExternalSignal[]> shape used
// by the pre-meeting brief. Moderates each account's signals in parallel.
export async function moderateBriefSignals(
  briefSignals: Record<string, ExternalSignal[]>,
): Promise<Record<string, ExternalSignal[]>> {
  const entries = Object.entries(briefSignals);
  if (entries.length === 0) return briefSignals;

  const moderated = await Promise.all(
    entries.map(async ([id, sigs]) => {
      const result = await moderateSignals(sigs);
      return [id, result] as const;
    }),
  );

  return Object.fromEntries(moderated);
}
