import type { IntegrationSpec } from "./types";

export const CHILIPIPER_SPEC: IntegrationSpec = {
  source: "Chili Piper",
  tagline: "Meeting router + scheduler.",
  direction: "read",
  auth: {
    method: "api_key",
    docsUrl:
      "https://help.chilipiper.com/hc/en-us/articles/360053799073-Configuring-REST-API",
    notes:
      "Edge API token generated in Admin Center > Integrations > API. Webhooks configured separately in Admin Center > Integrations > Custom Webhooks.",
  },
  baseUrl: "https://edge.chilipiper.com",
  setupFields: [
    {
      key: "subdomain",
      label: "Subdomain",
      type: "text",
      required: true,
      description:
        "Your Chili Piper subdomain (the part before .chilipiper.com).",
      placeholder: "acme",
    },
    {
      key: "edge_api_token",
      label: "Edge API token",
      type: "password",
      required: true,
      secret: true,
      description: "From Admin Center > Integrations > API.",
      placeholder: "cp_live_...",
    },
    {
      key: "webhook_shared_secret",
      label: "Webhook shared secret",
      type: "password",
      required: false,
      secret: true,
      description:
        "Auto-generated by Dugout. Paste into each Chili Piper Custom Webhook for HMAC verification.",
    },
    {
      key: "default_router_id",
      label: "Default router ID (optional)",
      type: "text",
      required: false,
      description: "Scope reads to a specific router. Leave blank for all.",
      placeholder: "router_abc123",
    },
  ],
  requiredScopes: [],
  webhooks: [
    {
      event: "Meeting Booked",
      description: "Fires for every new meeting from any source (form router, instant booker, concierge).",
    },
    {
      event: "Meeting Updated",
      description: "Fires when a meeting is reassigned or rescheduled.",
    },
    {
      event: "Meeting Canceled",
      description: "Fires when prospect or user cancels the meeting.",
    },
    {
      event: "Meeting No-Show",
      description: "Available in newer admin builds (verify in your tenant's UI).",
    },
  ],
  webhookSigning:
    "Shared-secret HMAC (assume SHA-256; verify against first delivery). Secret is set at webhook-registration time in the Admin Center UI.",
  rateLimit: "Not officially published. Keep Edge API under ~5 req/sec.",
  syncModel: "webhooks",
  dataFreshness: "Sub-second via webhook; 1 hr poll backfill",
  headlessSetup: false,
  keyGotchas: [
    "Two different base URLs trip everyone up: `api.chilipiper.com` for marketing/booking, `edge.chilipiper.com` for admin reads.",
    "Long-lived session tokens for automation require emailing Chili Piper Support - not self-service. Plan 1-3 day lag in customer setup.",
    "Webhook event-name strings are not stable across tenants (admin can rename). Key off the structural payload (`meetingId`, `status`, `cancelReason`), not the label.",
  ],
};
